lib/mailbase_web/router.ex
defmodule MailbaseWeb.Router do
  use MailbaseWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MailbaseWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/welcome", UserController, :logged_in
    get "/single_email", UserController, :new_single_email
    get "/add_rcv", ListController, :add_receiver
    resources "/user", UserController
    resources "/userdata", UserDataController, except: [:new, :create]
    resources "/list", ListController
    resources "/receivers", AddressController, except: [:show]
    resources "/schedules", ScheduleController

    get "/login", SessionController, :new
    post "/login", SessionController, :create
    delete "/login", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", MailbaseWeb do
  #   pipe_through :api
  # end
end

lib/mailbase_web/views/layout_view.ex
defmodule MailbaseWeb.LayoutView do
  use MailbaseWeb, :view
end

lib/mailbase_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Mailbase · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container" style="display: flex; align-items: center; justify-content: center;">
        <nav role="navigation" style="display: flex; align-items: center; justify-content: center; margin-top: 1rem">
          <ul>
            <%= if MailbaseWeb.Helpers.Auth.signed_in?(@conn) do %>
              <div style="display: flex; justify-content: flex-start; flex-direction: column;">
                <%= button "Wylogowanie", to: Routes.session_path(@conn, :delete), method: "delete" %>
                <div class="user-info">
                  <span style="display: inline">Zalogowano jako:</span>
                  <span style="display: inline"><%= @conn.assigns.current_user.login_mail %></span>
              </div>
            <% else %>
            <div style="display: flex; justify-content: flex-start; flex-direction: column;">
              <%= button "Logowanie", to: Routes.session_path(@conn, :new), method: "get" %>
              <%= button "Rejestracja", to: Routes.user_path(@conn, :new), method: "get" %>
            </div>
            <% end %>
          </ul>
        </nav>
        <a href="<%= Routes.user_path(@conn, :logged_in) %>" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/logo.jpg") %>" alt="Mailbase Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>