lib/mailbase_web/router.ex
defmodule MailbaseWeb.Router do
  use MailbaseWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MailbaseWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/welcome", UserController, :logged_in
    get "/single_email", UserController, :new_single_email
    get "/add_rcv", ListController, :add_receiver
    resources "/user", UserController
    resources "/userdata", UserDataController, except: [:new, :create]
    resources "/list", ListController
    resources "/receivers", AddressController, except: [:show]
    resources "/schedules", ScheduleController

    get "/login", SessionController, :new
    post "/login", SessionController, :create
    delete "/login", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", MailbaseWeb do
  #   pipe_through :api
  # end
end

lib/mailbase/accounts/user.ex
defmodule Mailbase.Accounts.User do
  use Ecto.Schema
  import Ecto.Changeset

  schema "users" do
    field :login_mail, :string
    field :login_password, :string

    has_one :user_data, Mailbase.AccountsData.UserData, on_delete: :delete_all
    has_many :lists, Mailbase.Lists.List, on_delete: :delete_all
    has_many :schedules, Mailbase.Schedules.Schedule, on_delete: :delete_all
    timestamps()
  end

  @doc false
  def changeset(user, attrs) do
    user
    |> cast(attrs, [:login_mail, :login_password])
    |> validate_required([:login_mail, :login_password])
    |> unique_constraint(:login_mail)
    |> validate_format(:login_mail, ~r/@/)
    |> validate_length(:login_password, min: 8, max: 16)
    |> update_change(:login_password, &Bcrypt.hash_pwd_salt/1)
  end
end

lib/mailbase_web/controllers/user_controller.ex
defmodule MailbaseWeb.UserController do
  use MailbaseWeb, :controller

  alias Mailbase.Lists
  alias Mailbase.Accounts
  alias Mailbase.Accounts.User
  alias Mailbase.AccountsData
  alias MailbaseWeb.Helpers

plug MailbaseWeb.Plugs.CheckAuth when action in [:index, :show, :edit, :logged_in]

  def index(conn, _params) do
    users = Accounts.list_users()
    render(conn, "index.html", users: users)
  end

  def new(conn, _params) do
    changeset = Accounts.change_user(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Accounts.create_user(user_params) do
      {:ok, user} ->
        add_user_data(user)
        conn
        |> put_session(:current_user_id, user.id)
        |> put_flash(:info, "Rejestracja przebiegła pomyślnie")
        |> redirect(to: Routes.user_path(conn, :logged_in))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    if Helpers.UserCompatibility.check_user(conn, id) do
      user = Accounts.get_user!(id)
      render(conn, "show.html", user: user)
    else
      conn
      |> put_flash(:error, "Nie masz dostępu do tych danych")
      |> redirect(to: Routes.user_path(conn, :index))
    end
  end

  def edit(conn, %{"id" => id}) do
    if Helpers.UserCompatibility.check_user(conn, id) do
      user = Accounts.get_user!(id)
      changeset = Accounts.change_user(user)
      render(conn, "edit.html", user: user, changeset: changeset)
    else
      conn
      |> put_flash(:error, "Nie masz dostępu do tych danych")
      |> redirect(to: Routes.user_path(conn, :index))
    end
  end

  def update(conn, %{"id" => id, "user" => user_params}) do
    user = Accounts.get_user!(id)

    case Accounts.update_user(user, user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "Użytkownik zaktualizowany")
        |> redirect(to: Routes.user_path(conn, :show, user))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    {:ok, _user} = Accounts.delete_user(user)

    conn
    |> put_flash(:info, "Użytkownik usunięty")
    |> redirect(to: Routes.user_path(conn, :index))
  end

  def logged_in(conn, _params) do
    IO.inspect conn
    c_user = conn.assigns.current_user
    render(conn, "logged_in.html", c_user: c_user)
  end


  defp add_user_data(user) do
    AccountsData.create_user_data(%{"company_name" => nil,
                                    "domain_name" => nil,
                                    "hosting_mail" => nil,
                                    "hosting_password" => nil,
                                    "port" => nil,
                                    "server_name" => nil,
                                    "user" => user,
                                    "user_id" => user.id})
  end

  def new_single_email(conn, _params) do

    #list_names = Lists.get_user_list_names(1)
    render(conn, "new_email.html")#, list_names: list_names)
  end

  def process_singe_email(conn, params) do
    IO.inspect params
  end

end

lib/mailbase_web/views/user_view.ex
defmodule MailbaseWeb.UserView do
  use MailbaseWeb, :view
end

lib/mailbase_web/templates/user/edit.html.eex
<h1>Edycja danych logowania</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :update, @user)) %>

<ul style = "list-style: none;">
  <li>
    <span><%= link "Wróć", to: Routes.user_path(@conn, :logged_in) %></span>
  </li>
  <li>
    <span><%= link "Edytuj dane kontaktowe", to: Routes.user_data_path(@conn, :edit, @user) %></span>
  </li>
</ul>

lib/mailbase_web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Panie, takiego wała. Coś się zepsuło.</p>
    </div>
  <% end %>

<div style = "display: flex; align-items: center; justify-content: center">
  <div>
      <%= label f, :email %>
      <%= text_input f, :login_mail %>
      <%= error_tag f, :login_mail %>

      <%= label f, :hasło %>
      <%= password_input f, :login_password %>
      <%= error_tag f, :login_password %>

      <div>
        <%= submit "Rejestruj" %>
      </div>
      <% end %>
    </div>
</div>

lib/mailbase_web/templates/user/form0.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Panie, takiego wała. Coś się zepsuło.</p>
    </div>
  <% end %>

<div style = "display: flex; align-items: center; justify-content: center">
  <div>
      <%= label f, :email %>
      <%= text_input f, :login_mail %>
      <%= error_tag f, :login_mail %>

      <%= label f, :hasło %>
      <%= password_input f, :login_password %>
      <%= error_tag f, :login_password %>

      <div>
        <%= submit "Rejestruj" %>
      </div>

  </div>
</div>
<% end %>

lib/mailbase_web/templates/user/index.html.eex
<h1>Lista użytkowników</h1>

<table>
  <thead>
    <tr>
      <th>Login mail</th>
      <th>Login password</th>
      <th>ID</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= user.login_mail %></td>
      <td><%= user.login_password %></td>
      <td><%= user.id %></td>

      <td>
        <%= link "Pokaż", to: Routes.user_path(@conn, :show, user) %>
        <%= link "Edytuj", to: Routes.user_path(@conn, :edit, user) %>
        <%= link "Usuń", to: Routes.user_path(@conn, :delete, user), method: :delete, data: [confirm: "Are you sure?"] %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

lib/mailbase_web/templates/user/logged_in.html.eex
<h1 style="display: flex; align-items: flex-start; justify-content: space-evenly;"> Witaj w bazie mailingowej</h1>
<div style="display: flex; flex-direction: row; align-items: flex-start; justify-content: space-evenly;">

<div style="display: flex; flex-direction: column; align-items: center; justify-content: center; order: 1;">
    <span><%= button "Edytuj dane logowania", to: Routes.user_path(@conn, :edit, @c_user), method: "get", class: "btna" %></span>
    <span><%= button "Edytuj dane kontaktowe", to: Routes.user_data_path(@conn, :edit, @c_user), method: "get", class: "btna" %></span>
    <span><%= button "Przeglądaj listy", to: Routes.list_path(@conn, :index), method: "get", class: "btna" %></span>
    <span><%= button "Dodaj listę", to: Routes.list_path(@conn, :new), method: "get", class: "btna" %></span>
    <span><%= button "Przeglądaj schedules", to: Routes.schedule_path(@conn, :index), method: "get", class: "btna" %></span>
    <span><%= button "Dodaj schedule", to: Routes.schedule_path(@conn, :new), method: "get", class: "btna" %></span>
</div>

<div style="display: flex; flex-direction: column; align-items: center; justify-content: center; order: 2;">
  <span><%= button "Wyślij maila", to: Routes.user_path(@conn, :new_single_email), method: "get", class: "btnb"%></span>
  <span><%= button "Xoxo", to: Routes.user_path(@conn, :logged_in), method: "get", class: "btnb"%></span>
  <span><%= button "Xoxo2", to: Routes.user_path(@conn, :logged_in), method: "get", class: "btnb"%></span>
</div>
</div>

lib/mailbase_web/templates/user/new.html.eex
<h1 style = "display: flex; align-items: center; justify-content: center">Rejestracja</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :create)) %>

lib/mailbase_web/templates/user/new_email.html.eex
<h1> Nowy email </h1>

<% form_for %{}, Routes.user_path(@conn, :process_single_email), fn f -> %>

  <%= label f, :matching_list %>
  <%= select f, :matching_list, ["aa", "bb"] %><!--, @list_names %>-->

  <%= label f, :email_title %>
  <%= text_input f, :email_title %>
  <%= error_tag f, :email_title %>

  <%= label f, :email_text %>
  <%= textarea f, :email_text %>
  <%= error_tag f, :email_text %>

  <div>
    <%= submit "Wyślij" %>
  </div>

<% end %>

<span><%= link "Wróć", to: Routes.user_path(@conn, :logged_in) %></span>

lib/mailbase_web/templates/user/show.html.eex
<h1>Witaj</h1>

<ul>

  <li>
    <strong>Login mail:</strong>
    <%= @user.login_mail %>
  </li>

  <li>
    <strong>Login password:</strong>
    <%= @user.login_password %>
  </li>

</ul>

<span><%= link "Edytuj dane logowania", to: Routes.user_path(@conn, :edit, @user) %></span>
||
<span><%= link "_list", to: Routes.user_path(@conn, :index) %></span>